/**
 * game.test.ts
 *
 * Two layers of tests:
 *
 * 1. Unit tests — verify internal consistency of the TypeScript game engine
 *    without any external reference (encode/decode round-trips, shape checks,
 *    invariants that must hold after every action).
 *
 * 2. Fixture tests — load tests/fixtures.json (generated by the Python
 *    implementation) and assert exact agreement on state fields,
 *    observation tensors, legal-action masks, and return values.
 */

import { readFileSync } from 'fs';
import { join } from 'path';
import { describe, expect, it } from 'vitest';

import {
  applyAction,
  buildObservation,
  CHALLENGE_ACTION,
  decodeBid,
  dealGame,
  encodeBid,
  getReturns,
  isChanceNode,
  isTerminal,
  legalActionsMask,
  newInitialState,
} from '../game';
import type { GameConfig, GameState } from '../types';

// ─── helpers ────────────────────────────────────────────────────────────────

function makeConfig(
  num_players = 2,
  hand_length = 3,
  num_digits = 3,
): GameConfig {
  const total_cards = num_players * hand_length;
  const max_bids    = hand_length * num_digits * num_players;
  const num_actions = max_bids + 1;
  const obs_size    = num_players + hand_length + 2 + 2 * max_bids * num_players;
  return { num_players, hand_length, num_digits, total_cards, max_bids, num_actions, obs_size };
}

/** Apply a sequence of actions (including deal) to a fresh initial state. */
function applySequence(config: GameConfig, actions: number[]): GameState {
  let s = newInitialState(config);
  for (const a of actions) s = applyAction(s, config, a);
  return s;
}

/** Deal specific hands via chance actions, then return the post-deal state. */
function dealWithActions(config: GameConfig, dealActions: number[]): GameState {
  let s = newInitialState(config);
  for (const a of dealActions) s = applyAction(s, config, a);
  expect(isChanceNode(s, config)).toBe(false);
  return s;
}

// ─── 1. Unit tests ────────────────────────────────────────────────────────────

describe('newInitialState', () => {
  it('creates correct shapes and sentinel values', () => {
    const cfg = makeConfig();
    const s = newInitialState(cfg);
    expect(s.hands.length).toBe(cfg.num_players);
    expect(s.hands[0].length).toBe(cfg.hand_length);
    expect(s.bid_history.length).toBe(cfg.max_bids);
    expect(s.bid_history[0].length).toBe(cfg.num_players);
    expect(s.challenge_history.length).toBe(cfg.max_bids);
    expect(s.deal_step).toBe(0);
    expect(s.current_player).toBe(0);
    expect(s.bid_originator).toBe(-1);
    expect(s.current_bid_action).toBe(-1);
    expect(s.num_challenges).toBe(0);
    expect(s.is_rebid).toBe(false);
    expect(s.winner).toBe(-1);
    expect(s.loser).toBe(-1);
  });

  it('isChanceNode is true and isTerminal is false initially', () => {
    const cfg = makeConfig();
    const s = newInitialState(cfg);
    expect(isChanceNode(s, cfg)).toBe(true);
    expect(isTerminal(s)).toBe(false);
  });
});

describe('decodeBid / encodeBid', () => {
  const cfg = makeConfig(2, 3, 3);

  it('round-trips all bid IDs', () => {
    for (let bidId = 0; bidId < cfg.max_bids; bidId++) {
      const { count, number } = decodeBid(bidId, cfg);
      expect(encodeBid(count, number, cfg)).toBe(bidId);
    }
  });

  it('correct values for bid_id=0', () => {
    const { count, number } = decodeBid(0, cfg);
    expect(count).toBe(1);
    expect(number).toBe(1);  // 1-indexed internally, matches Python
  });

  it('correct values for bid_id=max_bids-1', () => {
    const { count, number } = decodeBid(cfg.max_bids - 1, cfg);
    expect(count).toBe(cfg.num_players * cfg.hand_length);
    expect(number).toBe(cfg.num_digits);  // 1-indexed max
  });

  it('decode(encode(c,n)) == (c,n) for arbitrary (c,n)', () => {
    [[1, 1], [2, 2], [3, 3], [1, 3], [3, 1], [2, 3]].forEach(([c, n]) => {
      const bidId = encodeBid(c, n, cfg);
      expect(decodeBid(bidId, cfg)).toEqual({ count: c, number: n });
    });
  });
});

describe('deal phase', () => {
  const cfg = makeConfig(2, 3, 3);

  it('advances deal_step and fills hands in round-robin order', () => {
    // deal_step k → player = k % num_players, slot = floor(k / num_players)
    const dealActions = [1, 2, 0, 1, 2, 0];
    let s = newInitialState(cfg);
    for (let i = 0; i < dealActions.length; i++) {
      const player = i % cfg.num_players;
      const slot   = Math.floor(i / cfg.num_players);
      s = applyAction(s, cfg, dealActions[i]);
      expect(s.hands[player][slot]).toBe(dealActions[i] + 1);
    }
    expect(s.deal_step).toBe(cfg.total_cards);
    expect(isChanceNode(s, cfg)).toBe(false);
  });

  it('dealGame produces non-chance state with correct hand sizes', () => {
    const s = dealGame(cfg);
    expect(isChanceNode(s, cfg)).toBe(false);
    expect(s.hands.length).toBe(cfg.num_players);
    for (const h of s.hands) {
      expect(h.length).toBe(cfg.hand_length);
      for (const d of h) {
        expect(d).toBeGreaterThanOrEqual(1);
        expect(d).toBeLessThanOrEqual(cfg.num_digits);
      }
    }
  });
});

describe('legalActionsMask', () => {
  const cfg = makeConfig(2, 3, 3);

  it('all false before dealing is complete', () => {
    const s = newInitialState(cfg);
    const mask = legalActionsMask(s, cfg);
    expect(mask.every(v => !v)).toBe(true);
  });

  it('no challenge legal on first action, all bids legal', () => {
    const s = dealWithActions(cfg, [0, 1, 2, 1, 0, 2]);
    const mask = legalActionsMask(s, cfg);
    expect(mask[CHALLENGE_ACTION]).toBe(false);
    // All bid actions should be legal
    for (let a = 1; a <= cfg.max_bids; a++) expect(mask[a]).toBe(true);
  });

  it('after first bid: challenge legal, bids must be strictly higher', () => {
    const s = dealWithActions(cfg, [0, 1, 2, 1, 0, 2]);
    const afterBid = applyAction(s, cfg, 5); // action 5 = bid_id 4
    const mask = legalActionsMask(afterBid, cfg);
    expect(mask[CHALLENGE_ACTION]).toBe(true);
    // Actions ≤ 5 are illegal bids
    for (let a = 1; a <= 5; a++) expect(mask[a]).toBe(false);
    // Actions > 5 up to max_bids are legal
    for (let a = 6; a <= cfg.max_bids; a++) expect(mask[a]).toBe(true);
  });

  it('originator cannot bid again unless rebid is possible', () => {
    // P0 bids, then it's P1's turn, then P0's turn (but P0 is originator)
    const s = dealWithActions(cfg, [0, 1, 2, 1, 0, 2]);
    const s1 = applyAction(s, cfg, 3);   // P0 bids action 3
    const s2 = applyAction(s1, cfg, 5);  // P1 bids higher (action 5), now P1 is originator
    // Current player is P0 (not originator), so all higher bids legal
    const mask = legalActionsMask(s2, cfg);
    expect(mask[CHALLENGE_ACTION]).toBe(true);
    for (let a = 1; a <= 5; a++) expect(mask[a]).toBe(false);
    for (let a = 6; a <= cfg.max_bids; a++) expect(mask[a]).toBe(true);
  });

  it('rebid is legal when all non-originators have challenged', () => {
    // In 2-player: after P0 bids and P1 challenges, P0 may rebid (is_rebid_possible)
    const s = dealWithActions(cfg, [0, 1, 2, 1, 0, 2]);
    const s1 = applyAction(s, cfg, 5);   // P0 bids action 5
    const s2 = applyAction(s1, cfg, 0);  // P1 challenges → num_challenges=1 → is_rebid_possible
    // P0 turn: can rebid (all bids > 5) or challenge
    const mask = legalActionsMask(s2, cfg);
    expect(mask[CHALLENGE_ACTION]).toBe(true);
    for (let a = 1; a <= 5; a++) expect(mask[a]).toBe(false);
    for (let a = 6; a <= cfg.max_bids; a++) expect(mask[a]).toBe(true);
  });

  it('all actions false in terminal state', () => {
    // deal [1,2,1,0,2,1] → P0=[2,2,3], P1=[3,1,2]; bid "2×2" (action=5) → digit-2=3 ≥ 2 → P0 wins
    const s = applySequence(cfg, [1, 2, 1, 0, 2, 1, 5, 0, 0]);
    expect(isTerminal(s)).toBe(true);
    expect(legalActionsMask(s, cfg).every(v => !v)).toBe(true);
  });
});

describe('applyAction – bid', () => {
  const cfg = makeConfig(2, 3, 3);

  it('records bid in bid_history and updates bid state', () => {
    const s = dealWithActions(cfg, [0, 1, 2, 1, 0, 2]);
    const bidAction = 4; // bid_id=3
    const after = applyAction(s, cfg, bidAction);
    expect(after.current_bid_action).toBe(bidAction);
    expect(after.bid_originator).toBe(0);   // P0 bid
    expect(after.bid_history[3][0]).toBe(1); // bid_id=3, player=0
    expect(after.num_challenges).toBe(0);
    expect(after.is_rebid).toBe(false);
    expect(after.current_player).toBe(1);
  });

  it('is_rebid is true when originator bids again after a challenge', () => {
    const s = dealWithActions(cfg, [0, 1, 2, 1, 0, 2]);
    const s1 = applyAction(s, cfg, 4);   // P0 bids action 4, orig=P0
    const s2 = applyAction(s1, cfg, 0);  // P1 challenges
    const s3 = applyAction(s2, cfg, 6);  // P0 rebids action 6 (orig==current_player)
    expect(s3.is_rebid).toBe(true);
    expect(s3.bid_originator).toBe(0);
  });

  it('is_rebid resets to false when a different player bids after originator rebid', () => {
    const s = dealWithActions(cfg, [0, 1, 2, 1, 0, 2]);
    const s1 = applyAction(s, cfg, 3);   // P0 bids
    const s2 = applyAction(s1, cfg, 5);  // P1 bids higher → P1 is originator, not a rebid
    expect(s2.is_rebid).toBe(false);
    expect(s2.bid_originator).toBe(1);
  });
});

describe('applyAction – challenge', () => {
  const cfg = makeConfig(2, 3, 3);
  // deal [0,1,0,0,1,0] → P0=[1,1,2], P1=[2,1,1]
  // digit-1 total=4, digit-2 total=2, digit-3 total=0
  const deal = [0, 1, 0, 0, 1, 0];

  it('records challenge in challenge_history', () => {
    const s = dealWithActions(cfg, deal);
    const s1 = applyAction(s, cfg, 5);   // P0 bids action 5 (bid_id=4: "2×2" internally)
    const s2 = applyAction(s1, cfg, 0);  // P1 challenges
    expect(s2.challenge_history[4][1]).toBe(1); // bid_id=4 (action 5 - 1), player=1
    expect(s2.num_challenges).toBe(1);
  });

  it('bidder wins when matches >= count (P0 bids 2×2, digit-2=2 ≥ 2)', () => {
    const s = applySequence(cfg, [...deal, 5, 0, 0]); // deal, P0 bids 2×2, P1 ch, P0 ch
    expect(isTerminal(s)).toBe(true);
    expect(s.winner).toBe(0);
    expect(s.loser).toBe(-1);
  });

  it('bidder loses when matches < count (P0 bids 3×2, digit-2=2 < 3)', () => {
    const s = applySequence(cfg, [...deal, 8, 0, 0]); // P0 bids 3×2 (action=8), P1 ch, P0 ch
    expect(isTerminal(s)).toBe(true);
    expect(s.loser).toBe(0);
    expect(s.winner).toBe(-1);
  });

  it('bidder loses when digit is impossible (P0 bids 1×3, digit-3 count=0 < 1)', () => {
    const s = applySequence(cfg, [...deal, 3, 0, 0]); // P0 bids 1×3 (action=3), both challenge
    expect(isTerminal(s)).toBe(true);
    expect(s.loser).toBe(0);
    expect(s.winner).toBe(-1);
  });

  it('non-rebid game needs all num_players challenges to resolve', () => {
    const s = dealWithActions(cfg, deal);
    const s1 = applyAction(s, cfg, 5);   // P0 bids
    const s2 = applyAction(s1, cfg, 0);  // P1 challenges (1 of 2 needed)
    expect(isTerminal(s2)).toBe(false);
    const s3 = applyAction(s2, cfg, 0);  // P0 challenges (2 of 2 needed) → terminal
    expect(isTerminal(s3)).toBe(true);
  });

  it('rebid game needs only num_players-1 challenges to resolve', () => {
    const s = dealWithActions(cfg, deal);
    const s1 = applyAction(s, cfg, 5);   // P0 bids (orig=P0)
    const s2 = applyAction(s1, cfg, 0);  // P1 challenges → rebid possible
    const s3 = applyAction(s2, cfg, 7);  // P0 rebids action 7 (is_rebid=true)
    const s4 = applyAction(s3, cfg, 0);  // P1 challenges → num_challenges=1 == num_players-1 → terminal
    expect(isTerminal(s4)).toBe(true);
  });
});

describe('getReturns', () => {
  const cfg = makeConfig(2, 3, 3);
  // deal [0,1,0,0,1,0] → P0=[1,1,2], P1=[2,1,1]; digit-2=2, digit-3=0
  const deal = [0, 1, 0, 0, 1, 0];

  it('all zeros before terminal', () => {
    const s = dealWithActions(cfg, deal);
    expect(getReturns(s, cfg)).toEqual([0, 0]);
  });

  it('bidder wins: originator gets +(num_players-1), others get -1', () => {
    const s = applySequence(cfg, [...deal, 5, 0, 0]); // P0 bids 2×2, wins
    const r = getReturns(s, cfg);
    expect(r[0]).toBe(1);   // originator P0 wins: +(2-1) = +1
    expect(r[1]).toBe(-1);
  });

  it('bidder loses: originator gets -(num_players-1), others get +1', () => {
    const s = applySequence(cfg, [...deal, 8, 0, 0]); // P0 bids 3×2, loses
    const r = getReturns(s, cfg);
    expect(r[0]).toBe(-1);  // originator P0 loses: -(2-1) = -1
    expect(r[1]).toBe(1);
  });

  it('P1 as originator: P1 wins → P1 gets +1, P0 gets -1', () => {
    // P0 bids low (action=1), P1 raises (action=4 = "2×1"), P0+P1 challenge → P1 wins
    // deal [2,1,0,2,0,1] → P0=[3,1,1], P1=[2,3,2]: digit-1: P0=2, P1=0 → total=2 ≥ 2 → P1 wins
    const deal2 = [2, 1, 0, 2, 0, 1];
    const s = applySequence(cfg, [...deal2, 1, 4, 0, 0]);
    const r = getReturns(s, cfg);
    expect(s.bid_originator).toBe(1);
    expect(r[1]).toBe(1);
    expect(r[0]).toBe(-1);
  });
});

describe('buildObservation', () => {
  const cfg = makeConfig(2, 3, 3);
  const deal = [0, 1, 0, 0, 1, 0]; // P0=[1,1,2], P1=[2,1,1]

  it('has correct length', () => {
    const s = dealWithActions(cfg, deal);
    expect(buildObservation(s, 0, cfg).length).toBe(cfg.obs_size);
    expect(buildObservation(s, 1, cfg).length).toBe(cfg.obs_size);
  });

  it('player one-hot is correct', () => {
    const s = dealWithActions(cfg, deal);
    const obs0 = buildObservation(s, 0, cfg);
    const obs1 = buildObservation(s, 1, cfg);
    expect(obs0[0]).toBe(1); expect(obs0[1]).toBe(0);
    expect(obs1[0]).toBe(0); expect(obs1[1]).toBe(1);
  });

  it('private hand shows own digits, not opponent digits', () => {
    const s = dealWithActions(cfg, deal);
    const obs0 = buildObservation(s, 0, cfg);
    const obs1 = buildObservation(s, 1, cfg);
    // P0 hand starts at index 2 (after 2-element player one-hot)
    expect(Array.from(obs0.slice(2, 5))).toEqual([1, 1, 2]);
    expect(Array.from(obs1.slice(2, 5))).toEqual([2, 1, 1]);
  });

  it('hand is zeros during the deal phase', () => {
    const s = newInitialState(cfg);
    const obs = buildObservation(s, 0, cfg);
    expect(Array.from(obs.slice(2, 5))).toEqual([0, 0, 0]);
  });

  it('is_rebid bit set correctly', () => {
    const s = dealWithActions(cfg, deal);
    // is_rebid index = num_players + hand_length = 2 + 3 = 5
    const s1 = applyAction(s, cfg, 4);   // P0 bids
    const s2 = applyAction(s1, cfg, 0);  // P1 challenges
    const s3 = applyAction(s2, cfg, 6);  // P0 rebids → is_rebid=true
    expect(buildObservation(s3, 0, cfg)[5]).toBe(1);
    expect(buildObservation(s1, 0, cfg)[5]).toBe(0); // before rebid
  });

  it('bid_history bit set after a bid', () => {
    const s = dealWithActions(cfg, deal);
    const s1 = applyAction(s, cfg, 5); // bid_id=4, player=0
    const obs = buildObservation(s1, 0, cfg);
    // bid_history starts at index: num_players + hand_length + 2 = 7
    // offset for bid_id=4, player=0: 4*num_players + 0 = 8
    const bidHistStart = cfg.num_players + cfg.hand_length + 2;
    expect(obs[bidHistStart + 4 * cfg.num_players + 0]).toBe(1);
    // Player 1 did not bid at bid_id=4
    expect(obs[bidHistStart + 4 * cfg.num_players + 1]).toBe(0);
  });

  it('challenge_history bit set after a challenge', () => {
    const s = dealWithActions(cfg, deal);
    const s1 = applyAction(s, cfg, 5);  // P0 bids action 5 (bid_id=4)
    const s2 = applyAction(s1, cfg, 0); // P1 challenges
    const obs = buildObservation(s2, 1, cfg);
    const challHistStart = cfg.num_players + cfg.hand_length + 2 + cfg.max_bids * cfg.num_players;
    // challenge at bid_id=4, player=1: offset = 4*num_players + 1 = 9
    expect(obs[challHistStart + 4 * cfg.num_players + 1]).toBe(1);
    expect(obs[challHistStart + 4 * cfg.num_players + 0]).toBe(0);
  });

  it('players see different hands but same bid/challenge history', () => {
    const s = dealWithActions(cfg, deal);
    const s1 = applyAction(s, cfg, 5);
    const obs0 = buildObservation(s1, 0, cfg);
    const obs1 = buildObservation(s1, 1, cfg);
    // bid/challenge history is public — must be identical
    const histStart = cfg.num_players + cfg.hand_length + 2;
    for (let i = histStart; i < cfg.obs_size; i++) {
      expect(obs0[i]).toBe(obs1[i]);
    }
    // But hands differ
    expect(Array.from(obs0.slice(2, 5))).not.toEqual(Array.from(obs1.slice(2, 5)));
  });
});

// ─── 2. Fixture tests ────────────────────────────────────────────────────────

interface FixtureState {
  hands: number[][];
  deal_step: number;
  current_player: number;
  bid_originator: number;
  current_bid_action: number;
  num_challenges: number;
  is_rebid: boolean;
  winner: number;
  loser: number;
  bid_history: number[][];
  challenge_history: number[][];
}

interface FixtureStep {
  action: number;
  state: FixtureState;
  obs: Record<string, number[]>;
  legal_mask: boolean[];
  returns: number[];
  terminal: boolean;
}

interface FixtureSequence {
  name: string;
  steps: FixtureStep[];
}

interface FixtureScenario {
  deal_actions: number[];
  post_deal: { state: FixtureState; obs: Record<string, number[]>; legal_mask: boolean[]; returns: number[] };
  sequences: FixtureSequence[];
}

interface Fixtures {
  meta: { config: GameConfig };
  scenarios: FixtureScenario[];
}

const FIXTURES_PATH = join(__dirname, '../../tests/fixtures.json');
const fixtures: Fixtures = JSON.parse(readFileSync(FIXTURES_PATH, 'utf-8'));
const CONFIG: GameConfig = fixtures.meta.config;

function assertStateMatches(ts: GameState, py: FixtureState, label: string) {
  expect(ts.deal_step,           `${label} deal_step`).toBe(py.deal_step);
  expect(ts.current_player,      `${label} current_player`).toBe(py.current_player);
  expect(ts.bid_originator,      `${label} bid_originator`).toBe(py.bid_originator);
  expect(ts.current_bid_action,  `${label} current_bid_action`).toBe(py.current_bid_action);
  expect(ts.num_challenges,      `${label} num_challenges`).toBe(py.num_challenges);
  expect(ts.is_rebid,            `${label} is_rebid`).toBe(py.is_rebid);
  expect(ts.hands,               `${label} hands`).toEqual(py.hands);
  expect(ts.bid_history,         `${label} bid_history`).toEqual(py.bid_history);
  expect(ts.challenge_history,   `${label} challenge_history`).toEqual(py.challenge_history);
  expect(ts.winner,              `${label} winner`).toBe(py.winner);
  expect(ts.loser,               `${label} loser`).toBe(py.loser);
}

function assertObsMatches(ts: GameState, py: Record<string, number[]>, label: string, tol = 1e-5) {
  for (let p = 0; p < CONFIG.num_players; p++) {
    const tsObs = buildObservation(ts, p, CONFIG);
    const pyObs = py[String(p)];
    expect(tsObs.length, `${label} obs[${p}] length`).toBe(pyObs.length);
    for (let i = 0; i < pyObs.length; i++) {
      expect(tsObs[i], `${label} obs[${p}][${i}]`).toBeCloseTo(pyObs[i], tol);
    }
  }
}

function assertLegalMatches(ts: GameState, py: boolean[], label: string) {
  const mask = legalActionsMask(ts, CONFIG);
  expect(mask.length, `${label} mask length`).toBe(py.length);
  for (let i = 0; i < py.length; i++) {
    expect(mask[i], `${label} legal[${i}]`).toBe(py[i]);
  }
}

function assertReturnsMatch(ts: GameState, py: number[], label: string) {
  const r = getReturns(ts, CONFIG);
  expect(r, `${label} returns`).toEqual(py);
}

describe('fixture – game state, observations, legal masks, returns', () => {
  fixtures.scenarios.forEach((scenario, si) => {
    const tag = `scenario[${si}]`;

    it(`${tag}: post-deal state matches Python`, () => {
      const s = applySequence(CONFIG, scenario.deal_actions);
      assertStateMatches(s, scenario.post_deal.state, `${tag} post_deal`);
    });

    it(`${tag}: post-deal observations match Python`, () => {
      const s = applySequence(CONFIG, scenario.deal_actions);
      assertObsMatches(s, scenario.post_deal.obs, `${tag} post_deal`);
    });

    it(`${tag}: post-deal legal mask matches Python`, () => {
      const s = applySequence(CONFIG, scenario.deal_actions);
      assertLegalMatches(s, scenario.post_deal.legal_mask, `${tag} post_deal`);
    });

    scenario.sequences.forEach(seq => {
      const seqTag = `${tag}/${seq.name}`;

      it(`${seqTag}: each step state matches Python`, () => {
        let s = applySequence(CONFIG, scenario.deal_actions);
        for (const step of seq.steps) {
          s = applyAction(s, CONFIG, step.action);
          assertStateMatches(s, step.state, `${seqTag} after action ${step.action}`);
        }
      });

      it(`${seqTag}: each step observations match Python`, () => {
        let s = applySequence(CONFIG, scenario.deal_actions);
        for (const step of seq.steps) {
          s = applyAction(s, CONFIG, step.action);
          if (!step.terminal) {
            assertObsMatches(s, step.obs, `${seqTag} after action ${step.action}`);
          }
        }
      });

      it(`${seqTag}: each step legal mask matches Python`, () => {
        // Note: Python's legal_actions_mask has no terminal guard (the JAX driver
        // never calls it on terminal states), whereas TypeScript returns all-false
        // for terminal states.  We compare only non-terminal steps.
        let s = applySequence(CONFIG, scenario.deal_actions);
        for (const step of seq.steps) {
          s = applyAction(s, CONFIG, step.action);
          if (!step.terminal) {
            assertLegalMatches(s, step.legal_mask, `${seqTag} after action ${step.action}`);
          }
        }
      });

      it(`${seqTag}: terminal step returns match Python`, () => {
        const terminalStep = seq.steps.find(st => st.terminal);
        if (!terminalStep) return; // skip non-terminal sequences
        let s = applySequence(CONFIG, scenario.deal_actions);
        for (const step of seq.steps) {
          s = applyAction(s, CONFIG, step.action);
          if (step.terminal) {
            assertReturnsMatch(s, step.returns, `${seqTag} terminal`);
          }
        }
      });
    });
  });
});
