/**
 * network.test.ts
 *
 * 1. Unit tests — verify legalPolicy and networkForward match the documented
 *    _legal_policy formula from rnad.py using small hand-crafted inputs.
 *
 * 2. Fixture tests — load tests/fixtures.json (generated by the Python
 *    implementation with the actual checkpoint) and verify the TypeScript
 *    forward pass produces identical logits and policy probabilities.
 *    These tests confirm that loading the checkpoint and running inference
 *    in the browser gives the same result as the Python agent.
 */

import { readFileSync } from 'fs';
import { join } from 'path';
import { describe, expect, it } from 'vitest';

import { legalPolicy, networkForward } from '../network';
import { loadCheckpointBytes } from '../checkpoint';
import type { NetworkWeights } from '../types';

// ─── 1. Unit tests ────────────────────────────────────────────────────────────

describe('legalPolicy', () => {
  /** Rebuild the expected output using the Python _legal_policy formula. */
  function referenceLegalPolicy(logits: number[], legal: boolean[]): number[] {
    const n = logits.length;
    const lMin = Math.min(...logits);
    // Replace illegal with l_min
    const masked = logits.map((v, i) => (legal[i] ? v : lMin));
    // Subtract max
    const lMax = Math.max(...masked);
    const shifted = masked.map(v => v - lMax);
    // Multiply by legal (illegal → 0)
    const gated = shifted.map((v, i) => (legal[i] ? v : 0));
    // Exp and mask
    const exp = gated.map((v, i) => (legal[i] ? Math.exp(v) : 0));
    const sum = exp.reduce((a, b) => a + b, 0);
    return exp.map(v => v / sum);
  }

  it('sums to 1 for uniform logits with some illegal actions', () => {
    const logits = new Float32Array([1, 1, 1, 1, 1]);
    const legal  = [true, false, true, false, true];
    const pi = legalPolicy(logits, legal);
    expect(pi.reduce((a, b) => a + b, 0)).toBeCloseTo(1, 5);
    expect(pi[1]).toBe(0);
    expect(pi[3]).toBe(0);
    expect(pi[0]).toBeCloseTo(1 / 3, 5);
  });

  it('all illegal except one → probability 1 on legal action', () => {
    const logits = new Float32Array([5, -10, 3, 2]);
    const legal  = [false, true, false, false];
    const pi = legalPolicy(logits, legal);
    expect(pi[1]).toBeCloseTo(1, 5);
    expect(pi[0] + pi[2] + pi[3]).toBeCloseTo(0, 5);
  });

  it('illegal actions get zero probability', () => {
    const logits = new Float32Array([3, 1, 4, 1, 5]);
    const legal  = [true, false, true, false, true];
    const pi = legalPolicy(logits, legal);
    expect(pi[1]).toBe(0);
    expect(pi[3]).toBe(0);
    expect(pi.reduce((a, b) => a + b, 0)).toBeCloseTo(1, 5);
  });

  it('matches reference _legal_policy formula on random-ish inputs', () => {
    const logits = [0.5, -1.2, 3.0, 0.0, -0.5, 2.1];
    const legal  = [true, false, true, true, false, true];
    const tsOut  = legalPolicy(new Float32Array(logits), legal);
    const ref    = referenceLegalPolicy(logits, legal);
    for (let i = 0; i < logits.length; i++) {
      expect(tsOut[i]).toBeCloseTo(ref[i], 5);
    }
  });

  it('higher logit gets higher probability (among legal actions)', () => {
    const logits = new Float32Array([1, 0, 5, 0, 2]);
    const legal  = [true, true, true, false, true];
    const pi = legalPolicy(logits, legal);
    expect(pi[2]).toBeGreaterThan(pi[4]);
    expect(pi[4]).toBeGreaterThan(pi[0]);
    expect(pi[0]).toBeGreaterThan(pi[1]);
  });

  it('numerically stable with large logit differences', () => {
    // Without the subtract-max trick, exp(100) would overflow
    const logits = new Float32Array([100, -100, 50]);
    const legal  = [true, true, true];
    const pi = legalPolicy(logits, legal);
    expect(pi.reduce((a, b) => a + b, 0)).toBeCloseTo(1, 5);
    expect(isNaN(pi[0])).toBe(false);
    expect(pi[0]).toBeGreaterThan(0.99);
  });
});

describe('networkForward', () => {
  /** Build a tiny 1-hidden-layer network with known weights. */
  function tinyWeights(): NetworkWeights {
    // 3-in → 2-hidden → 2-out
    // hidden kernel [3×2]: identity-ish
    const hKernel = new Float32Array([1, 0,   0, 1,   0, 0]);  // [3][2]
    const hBias   = new Float32Array([0.1, -0.1]);
    // logit kernel [2×2]: swap
    const lKernel = new Float32Array([0, 1,   1, 0]);           // [2][2]
    const lBias   = new Float32Array([0, 0]);
    return {
      hidden: [{ kernel: hKernel, bias: hBias, inSize: 3, outSize: 2 }],
      logit:  { kernel: lKernel, bias: lBias, inSize: 2, outSize: 2 },
      numLayers: 1,
    };
  }

  it('produces output of length num_actions', () => {
    const obs   = new Float32Array([1, 0, 1]);
    const legal = [true, true];
    const pi = networkForward(obs, legal, tinyWeights());
    expect(pi.length).toBe(2);
  });

  it('sums to 1', () => {
    const obs   = new Float32Array([1, 2, 3]);
    const legal = [true, false];
    const pi = networkForward(obs, legal, tinyWeights());
    expect(pi.reduce((a, b) => a + b, 0)).toBeCloseTo(1, 5);
  });

  it('zero obs → all-zero hidden activations after relu → uniform over legal actions', () => {
    const obs   = new Float32Array(3).fill(0);
    const legal = [true, true];
    const pi = networkForward(obs, legal, tinyWeights());
    // After relu, hidden = relu([0+0.1, 0-0.1]) = [0.1, 0.0]
    // logit = kernel^T @ [0.1, 0] + [0,0] = [0*0.1+1*0, 1*0.1+0*0] = [0, 0.1]
    // legal_policy([0, 0.1]) → softmax → ~[0.475, 0.525]
    expect(pi[0] + pi[1]).toBeCloseTo(1, 5);
    expect(pi[1]).toBeGreaterThan(pi[0]);
  });

  it('relu correctly suppresses negative pre-activations', () => {
    // obs = [0,0,0] → hidden pre-relu = [0.1, -0.1] → after relu = [0.1, 0]
    const obs   = new Float32Array(3).fill(0);
    const legal = [true, true];
    const w = tinyWeights();
    const pi = networkForward(obs, legal, w);
    // hidden[1] is relu'd to 0, only hidden[0]=0.1 contributes
    // logit = [0*0.1+1*0, 1*0.1+0*0] = [0, 0.1]
    // Both legal → second action more likely
    expect(pi[1]).toBeGreaterThan(pi[0]);
  });
});

// ─── 2. Fixture tests (Python agent vs TypeScript agent) ─────────────────────

interface NetworkFixture {
  name: string;
  player: number;
  observation: number[];
  legal_mask: boolean[];
  expected_logits: number[];
  expected_policy: number[];
}

interface Fixtures {
  network_tests: NetworkFixture[] | null;
}

const FIXTURES_PATH = join(__dirname, '../../tests/fixtures.json');
const fixtures: Fixtures = JSON.parse(readFileSync(FIXTURES_PATH, 'utf-8'));

describe('fixture – network forward pass matches Python agent', () => {
  if (!fixtures.network_tests) {
    it.skip('no network fixtures (run generate_fixtures.py --checkpoint ...)', () => {});
    return;
  }

  // Load the actual checkpoint once for all network tests
  const CKPT_PATH = join(__dirname, '../../../agent_40000.msgpack');
  let weights: NetworkWeights | null = null;
  try {
    const buf = readFileSync(CKPT_PATH);
    weights = loadCheckpointBytes(buf.buffer as ArrayBuffer).weights;
  } catch {
    // Checkpoint not available in this environment — skip gracefully
  }

  fixtures.network_tests.forEach(tc => {
    it(`${tc.name}: TypeScript forward pass matches Python`, () => {
      if (!weights) {
        // Skip if checkpoint file is not present
        return;
      }

      const obs   = new Float32Array(tc.observation);
      const legal = tc.legal_mask;

      // Import legalPolicy so we can also test the pre-policy logit path
      // (networkForward includes the legalPolicy step, so we compare the final policy)
      const policy = networkForward(obs, legal, weights);

      expect(policy.length, `${tc.name} policy length`).toBe(tc.expected_policy.length);

      // Policy probabilities: agree within float32 rounding tolerance (~1e-5)
      for (let i = 0; i < policy.length; i++) {
        expect(policy[i], `${tc.name} policy[${i}]`).toBeCloseTo(tc.expected_policy[i], 4);
      }

      // Illegal actions must be exactly zero in both
      for (let i = 0; i < legal.length; i++) {
        if (!legal[i]) {
          expect(policy[i], `${tc.name} illegal action ${i} should be 0`).toBe(0);
        }
      }

      // Policy sums to 1
      const sum = Array.from(policy).reduce((a, b) => a + b, 0);
      expect(sum, `${tc.name} policy sums to 1`).toBeCloseTo(1, 4);
    });
  });
});
